import { GoogleGenAI } from "@google/genai";

// Initialize Gemini AI
const apiKey = process.env.API_KEY || ''; // Ideally, this comes from env in a real build
const ai = new GoogleGenAI({ apiKey });

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string,
  mimeType: string = 'image/png'
): Promise<string> => {
  try {
    const model = 'gemini-2.5-flash-image';
    
    // Remove header if present (e.g., "data:image/png;base64,")
    const data = base64Image.split(',')[1] || base64Image;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: data,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Check for image in response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
       for (const part of candidates[0].content.parts) {
         if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
         }
       }
    }
    
    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};
